// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAssignedReviews() {
  return window['go']['main']['App']['GetAssignedReviews']();
}

export function GetCompletedReviews() {
  return window['go']['main']['App']['GetCompletedReviews']();
}

export function GetPullRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPullRequest'](arg1, arg2, arg3);
}

export function GetPullRequestsToReviewForUser() {
  return window['go']['main']['App']['GetPullRequestsToReviewForUser']();
}
