// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {githubservice} from '../models';

export function GetAssignedPullRequestsForUser():Promise<Array<githubservice.PullRequest>>;

export function GetAssignedReviews():Promise<Array<githubservice.Issue>>;

export function GetCompletedReviews():Promise<Array<githubservice.Issue>>;

export function GetPullRequest(arg1:string,arg2:string,arg3:number):Promise<githubservice.PullRequest>;

export function GetReviewedPullRequestsForUser():Promise<Array<githubservice.PullRequest>>;
